[package]
name = "gpu-clear-screen"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies.gpu-common]
path = "../gpu-common"

[dependencies.sdl3-sys]
path = "../../sdl3-sys"

[dependencies.sdl3-main]
path = "../../sdl3-main"
