[package]
name = "gpu-basic-triangle"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies.gpu-common]
path = "../gpu-common"

[dependencies.sdl3-sys]
path = "../../sdl3-sys"

[dependencies.sdl3-main]
path = "../../sdl3-main"
