[package]
name = "gpu-common"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"

[dependencies.sdl3-sys]
path = "../../sdl3-sys"
