name: "Github Lockdown"

on:
  issues:
    types: opened
  pull_request_target:
    types: opened

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v4
        with:
          issue-comment: "This repo is a mirror. Please submit issues and pull requests at <https://codeberg.org/maia/sdl3-sys-rs>. Thank you."
          pr-comment: "This repo is a mirror. Please submit issues and pull requests at <https://codeberg.org/maia/sdl3-sys-rs>. Thank you."
